using EFSharpGen.Design.Models;

namespace EFSharpGen.Generators;

/// <summary>
/// A service to combine pieces of code generated by the provided code generators.
/// </summary>
public interface ICodeCombiner
{
    /// <summary>
    /// Combines pieces of code generated by the provided code generators. Τhe
    /// pieces will be combined in the same order the generators are provided.
    /// </summary>
    /// <param name="entity">The <see cref="Entity"/> for which the code will be
    /// generated.</param>
    /// <param name="generators">An array of code generators which will generate
    /// the code pieces.</param>
    /// <returns>The combined code.</returns>
    string CombineCode(Entity entity, params ICodeGenerator[] generators);
}
