using EFSharpGen.Design.Models;

using Microsoft.Extensions.Options;

namespace EFSharpGen.Generators.Entities;

/// <summary>
/// An implementation to generate the code for the directives of an entity.
/// </summary>
/// <param name="options">The application options.</param>
public class EntityDirectivesCodeGenerator(IOptions<Options> options) :
    IEntityDirectiveCodeGenerator
{
    /// <summary>
    /// Generates the code for the directives of an entity.
    /// </summary>
    /// <param name="entity">The <see cref="Entity"/> for which the code will be
    /// generated.</param>
    /// <returns>The code for the directives of an entity.</returns>
    public virtual string? Code(Entity entity)
    {
        if (options.Value.NullableReferenceTypes &&
            options.Value.AutoGeneratedTag)
        {
            return "#nullable enable" + Environment.NewLine;
        }

        return null;
    }
}
