using EFSharpGen.Design;
using EFSharpGen.Design.Drawio;
using EFSharpGen.Generators;
using EFSharpGen.Generators.Configurations;
using EFSharpGen.Generators.Configurations.Postgres;
using EFSharpGen.Generators.Entities;
using EFSharpGen.Miscellaneous;

using Microsoft.Extensions.DependencyInjection;

namespace EFSharpGen;

/// <summary>
/// Extensions for the <see cref="IServiceCollection"></see>.
/// </summary>
public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Adds the EFSharpGen services with configuration.
    /// </summary>
    /// <param name="services">The <see cref="IServiceCollection"></see> to add
    /// services to.</param>
    /// <param name="configureOptions">An <see cref="Action{T}"></see> to
    /// configure the provided <see cref="Options"></see>.</param>
    /// <returns>The same service collection so that multiple calls can be
    /// chained.</returns>
    public static IServiceCollection AddEFSharpGen(
        this IServiceCollection services, Action<Options> configureOptions)
    {
        return services

            .Configure(configureOptions)

            .AddSingleton<ICodeEngine, CodeEngine>()
            .AddSingleton<IAppContext, AppContext>()

            .AddSingleton<IFileCreator, FileCreator>()
            .AddSingleton<IFileRegistry, FileRegistry>()
            .AddSingleton<ICodeCombiner, CodeCombiner>()
            .AddSingleton<ICodeFormatter, CodeFormatter>()

            .AddSingleton<IAutoGeneratedTagCodeGenerator, AutoGeneratedTagCodeGenerator>()
            .AddSingleton<INamespaceCodeGenerator, NamespaceCodeGenerator>()
            .AddSingleton<IEnumCodeGenerator, EnumCodeGenerator>()
            .AddSingleton<ITypeProvider, TypeProvider>()

            .AddSingleton<ISchemaProvider, DrawioSchemaProvider>()
            .AddSingleton<IEFConfigurationProvider, PostgresEFConfigurationProvider>()

            .AddSingleton<IFileGenerator, EntityFileGenerator>()
            .AddSingleton<IFileGenerator, ConfigurationFileGenerator>()

            .AddSingleton<IEntityPropertyCodeGenerator, EntityPropertyCodeGenerator>()
            .AddSingleton<IEntityReferenceNavigationCodeGenerator, EntityReferenceNavigationCodeGenerator>()
            .AddSingleton<IEntityCollectionNavigationCodeGenerator, EntityCollectionNavigationCodeGenerator>()
            .AddSingleton<IEntityDirectiveCodeGenerator, EntityDirectivesCodeGenerator>()
            .AddSingleton<IEntityUsingCodeGenerator, EntityUsingCodeGenerator>()
            .AddSingleton<IEntityNamespaceCodeGenerator, EntityNamespaceCodeGenerator>()
            .AddSingleton<IEntityEnumCodeGenerator, EntityEnumsCodeGenerator>()
            .AddSingleton<IEntityClassDeclarationCodeGenerator, EntityClassDeclarationCodeGenerator>()
            .AddSingleton<IEntityPrimaryKeyCodeGenerator, EntityPrimaryKeyCodeGenerator>()
            .AddSingleton<IEntitySimplePropertyCodeGenerator, EntitySimplePropertyCodeGenerator>()
            .AddSingleton<IEntityOneToOneReferenceNavigationCodeGenerator, EntityOneToOneReferenceNavigationCodeGenerator>()
            .AddSingleton<IEntityOneToNReferenceNavigationCodeGenerator, EntityOneToNReferenceNavigationCodeGenerator>()
            .AddSingleton<IEntityManyToManyReferenceNavigationCodeGenerator, EntityManyToManyReferenceNavigationCodeGenerator>()
            .AddSingleton<IEntityOneToManyCollectionNavigationCodeGenerator, EntityOneToManyCollectionNavigationCodeGenerator>()
            .AddSingleton<IEntityManyToManyCollectionNavigationCodeGenerator, EntityManyToManyCollectionNavigationCodeGenerator>()

            .AddSingleton<IConfigurationUsingCodeGenerator, ConfigurationUsingCodeGenerator>()
            .AddSingleton<IConfigurationNamespaceCodeGenerator, ConfigurationNamespaceCodeGenerator>()
            .AddSingleton<IConfigurationClassDeclarationCodeGenerator, ConfigurationClassDeclarationCodeGenerator>()
            .AddSingleton<IConfigurationConfigureMethodDeclarationCodeGenerator, ConfigurationConfigureMethodDeclarationCodeGenerator>()
            .AddSingleton<IConfigurationTableCodeGenerator, ConfigurationTableCodeGenerator>()
            .AddSingleton<IConfigurationEnumConstraintCodeGenerator, ConfigurationEnumConstraintCodeGenerator>()
            .AddSingleton<IConfigurationCompositeKeyCodeGenerator, ConfigurationCompositeKeyCodeGenerator>()
            .AddSingleton<IConfigurationPrimaryKeyCodeGenerator, ConfigurationPrimaryKeyCodeGenerator>();
    }
}
